name: pytorch
channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=25.1
- pip:
  - --extra-index-url https://download.pytorch.org/whl/cu128
  - polars==1.30.0
  - plotly==6.1.2
  - pillow==11.0.0
  - nbformat==5.10.4
  - torch==2.7.0+cu128
  - torchvision==0.22.0+cu128
  - torchinfo==1.8.0
  - lightning==2.5.1.post0
  - mlflow==2.22.0
  - psutil==7.0.0
  - pynvml==12.0.0